Everything except `param allfirmware` back to normal.

diff --git a/ts/build/jpmc/bin/build-jpmc-config b/ts/build/jpmc/bin/build-jpmc-config
--- a/ts/build/jpmc/bin/build-jpmc-config
+++ b/ts/build/jpmc/bin/build-jpmc-config
@@ -133,7 +133,7 @@ adjust_timezone
 echo
 echo "Starting ThinStation build."
 echo
-build_thinstation || { echo "[ERROR] ThinStation build failed... script will now exit.  Please check for errors above." ; return 1 ; }
+build_thinstation || { echo "[ERROR] ThinStation build failed... script will now exit.  Please check for errors above." ; exit 1 ; }
 
 
 
